### ISSUE TITLE
Modify font size and adjust image

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/app-icon-generator-website#1]
Modify the h1 in Home.jsx to have larger text and align the image underneath the h1 using Tailwind classes.

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by nikohoffren** [comment]
> Can I get assigned? let me know how to start.

Sure, go ahead. README.md has instructions of how to proceed. Modify the h1 in Home.jsx to have larger text and align the image underneath the h1 using Tailwind classes.
